export default {
  products: [
    {
      _id: "111111111111111111111111",
      name: "Full-Zip Running Shirts",
      category: "Shirts",
      image: "/images/product-1.jpg",
      price: 100,
      brand: "Armani",
      rating: 4.5,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "222222222222222222222222",
      name: "Nike Full-Zip Hoodie Mens Workout",
      category: "Shirts",
      image: "/images/product-2.jpg",
      price: 200,
      brand: "Nike",
      rating: 5,
      numReviews: 12,
      countInStock: 20,
    },
    {
      _id: "3",
      name: "Adidas Mens Long Sleevs Hoodie",
      category: "Shirts",
      image: "/images/product-3.jpg",
      price: 50,
      brand: "Adidaas",
      rating: 4,
      numReviews: 200,
      countInStock: 3,
    },
    {
      _id: "4",
      name: "Under Armour Mens Sport-style Pants",
      category: "Pants",
      image: "/images/product-4.jpg",
      price: 100,
      brand: "Champion",
      rating: 5,
      numReviews: 150,
      countInStock: 6,
    },
    {
      _id: "5",
      name: "Champion Polo Shirt",
      category: "Shirts",
      image: "/images/product-5.jpg",
      price: 20,
      brand: "Champion",
      rating: 3,
      numReviews: 10,
      countInStock: 6,
    },
    {
      _id: "6",
      name: "Arkterix Jogger Pants",
      category: "Pants",
      image: "/images/product-6.jpg",
      price: 50,
      brand: "Arkterix",
      rating: 4.5,
      numReviews: 100,
      countInStock: 10,
    },
  ],
};
